/************************************************************************************

	AstroMenace
	Hardcore 3D space scroll-shooter with spaceship upgrade possibilities.
	Copyright (c) 2006-2018 Mikhail Kurinnoi, Viewizard


	AstroMenace is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	AstroMenace is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with AstroMenace. If not, see <https://www.gnu.org/licenses/>.


	Web Site: https://www.viewizard.com/
	Project: https://github.com/viewizard/astromenace
	E-mail: viewizard@viewizard.com

*************************************************************************************/

#include "../core/core.h"
#include "../config/config.h"

namespace {

// empirical found "everage load value" for one texture asset
// small value mean that asset loads fast, big value - slow
constexpr unsigned TextureLoadValue{200};

struct sTextureAsset {
	std::string FileName;
	// alpha channel related
	bool Alpha;
	eAlphaCreateMode AlphaMode;
	// filtering related
	eTextureWrapMode TextWrap;
	eTextureBasicFilter TextFilter;
	bool NeedAnisotropy;
	bool MipMap;
};

// make sure, that all textures are added before first access,
// instead of sfx and models3d, texture will not loaded on access
const std::vector<sTextureAsset> TextureAssetArray{
	{"menu/astromenace.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button384_back.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button384_in.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button384_out.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button256_back.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button256_in.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button256_out.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button256_off.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/blackpoint.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/whitepoint.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/line.tga",
					true, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/perc.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/perc_none.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/checkbox_main.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/checkbox_in.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/workshop_panel1.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/workshop_panel1+.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/workshop_panel2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/workshop_panel2+.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/workshop_panel3.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/workshop_panel4.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/workshop_panel5.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/ammo.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/en/menu/button_weaponry_out.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/en/menu/button_weaponry_in.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/de/menu/button_weaponry_out.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/de/menu/button_weaponry_in.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/ru/menu/button_weaponry_out.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/ru/menu/button_weaponry_in.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/pl/menu/button_weaponry_out.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/pl/menu/button_weaponry_in.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/back_spot.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/back_spot2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/dialog512_256.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/dialog512_512.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/dialog768_600.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/panel444_333_back.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/panel444_333_border.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/panel800_444_back.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button_dialog200_out.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button_dialog200_in.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button_dialog200_off.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button_dialog128_out.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button_dialog128_in.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/button_dialog128_off.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/arrow_list_up.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/arrow_list_down.tga",
					true,  eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission1_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission2_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission3_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission4_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission5_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission6_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission7_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission8_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission9_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission10_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission11_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission12_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission13_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission14_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"script/mission15_icon.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_engine1.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_engine2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_engine3.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_engine4.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_mechan1.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_mechan2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_mechan3.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_mechan4.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_power1.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_power2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_power3.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_power4.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_protect1.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_protect2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_protect3.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_protect4.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_target1.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_target2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_target3.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_target4.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/system_empty.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon1_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon2_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon3_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon4_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon5_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon6_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon7_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon8_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon9_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon10_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon11_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon12_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon13_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon14_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon15_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon16_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon17_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon18_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon19_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon_on_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/weapon_empty_icon.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/cursor.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"menu/cursor_shadow.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"gfx/flare.tga",
					true, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"gfx/flare1.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"gfx/flare2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"gfx/flare3.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"gfx/trail1.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"gfx/trail2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"gfx/trail3.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"gfx/trail4.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"gfx/trail5.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"game/nums.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/ammo.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/energy.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/game_panel.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/game_panel2.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/game_panel_el.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/game_num.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/weapon_panel_left.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/weapon_panel_right.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/weapon_ammo.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"game/weapon_energy.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/en/game/mission.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/en/game/missionfailed.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/en/game/pause.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/de/game/mission.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/de/game/missionfailed.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/de/game/pause.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/ru/game/mission.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/ru/game/missionfailed.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"lang/ru/game/pause.tga",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/tile_back.tga",
					true, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"skybox/tile_stars.tga",
					true, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-text00.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-text04.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-text05.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-text06.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-text07.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-text08.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-text09.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-text10.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-illum01.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-illum02.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-illum03.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/sf-illum04.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/lnch12.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/lnch34.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/earthfighter/rockets.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/mine/mine1.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/mine/mine1i.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/mine/mine2.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/mine/mine2i.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/mine/mine3.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/mine/mine3i.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/mine/mine4.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/mine/mine4i.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienfighter/al-text04.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienfighter/al-illum04.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/gr-01.vw2d",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/gr-02.vw2d",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/gr-03.vw2d",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/gr-04.vw2d",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/normalmap/bomber_nm.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/gr-05.vw2d",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/gr-06.vw2d",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/gr-07.vw2d",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/track.vw2d",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/turret/turrets.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/spacebase/allalpha.tga",
					true, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/spacebase/metal.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/space/asteroid-01.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/planet/asteroid.tga",
					true, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/planet/clouds.tga",
					true, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/planet/q_class2.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/planet/a_class4.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/planet/m_class7.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/planet/d_class3.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/normalmap/m_class7_nm.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/normalmap/d_class3_nm.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/normalmap/a_class4_nm.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/normalmap/planet_asteroids_nm.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/normalmap/q_class2_nm.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienmothership/alm-text02.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienmothership/alm-text03.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienmothership/alm-text04.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienmothership/alm-text08.vw2d",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienmothership/alm-illum02.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienmothership/alm-illum03.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienmothership/alm-illum04.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/alienmothership/alm-illum08.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/normalmap/alien_mothership_nm.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/building/bld.vw2d",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/normalmap/buildings_nm.tga",
					false, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"models/building/bld_illum.vw2d",
					true, eAlphaCreateMode::EQUAL, eTextureWrapMode::REPEAT,
					eTextureBasicFilter::TRILINEAR, true, true},
	{"skybox/1/skybox_back6.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/1/skybox_bottom4.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/1/skybox_front5.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/1/skybox_left2.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/1/skybox_right1.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/1/skybox_top3.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/2/skybox_back6.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/2/skybox_bottom4.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/2/skybox_front5.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/2/skybox_left2.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/2/skybox_right1.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
	{"skybox/2/skybox_top3.tga",
					false, eAlphaCreateMode::GREYSC, eTextureWrapMode::CLAMP_TO_EDGE,
					eTextureBasicFilter::BILINEAR, false, false},
};

} // unnamed namespace


/*
 * Get all texture assets load value.
 */
unsigned GetTextureAssetsLoadValue()
{
	return TextureAssetArray.size() * TextureLoadValue;
}

/*
 * Cycle with function call on each texture asset load.
 */
void ForEachTextureAssetLoad(std::function<void (unsigned AssetValue)> function)
{
	vw_SetTextureAlpha(0, 0, 0);

	for (auto &tmpAsset : TextureAssetArray) {
		vw_SetTextureProp(tmpAsset.TextFilter,
				  tmpAsset.NeedAnisotropy ? GameConfig().AnisotropyLevel : 1,
				  tmpAsset.TextWrap, tmpAsset.Alpha, tmpAsset.AlphaMode, tmpAsset.MipMap);
		vw_LoadTexture(tmpAsset.FileName);
		function(TextureLoadValue);
	}
}

/*
 * Change anisotropy level for all textures that was loaded with anisotropy.
 */
void ChangeTexturesAnisotropyLevel()
{
	for (auto &tmpAsset : TextureAssetArray) {
		if (tmpAsset.NeedAnisotropy) {
			GLtexture tmpTexture = vw_FindTextureByName(tmpAsset.FileName);
			vw_BindTexture(0, tmpTexture);
			vw_SetTextureAnisotropy(GameConfig().AnisotropyLevel);
		}
	}
	vw_BindTexture(0, 0);
}
